site: OpenPupil.io
url: #yoururl
title: OpenPupil
description: A community-driven database of open-source pupil datasets.
summary: A curation of open-source pupil datasets compiled by researcher from different fields.
github: "https://github.com/openPupil"
permalink: pretty

#baseurl: "/openpupilwebsite"

highlighter: rouge # highlighter' was none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: false
    sort_by: front-page-order
    permalink: /:name
  legal:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  software:
    output: true
    permalink: /:year/:month/:day/:slug
  people:
    output: false
    permalink: /:name
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
